route:
  receiver: web.hook
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 2m

receivers:
  - name: web.hook
    webhook_configs:
      - url: "http://webhook:5001/"
        send_resolved: true
 
