apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  namespace: guestbook
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000  # ✅ Map to container's exposed port
  selector:
    app: guestbook
    tier: frontend
